import { copyFileSync, mkdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { defineConfig, type DefaultTheme } from 'vitepress';

// Generated by `npm run docs:api`, which the docs scripts run first.
const apiSidebar = JSON.parse(
  readFileSync(new URL('../api/typedoc-sidebar.json', import.meta.url), 'utf8'),
) as DefaultTheme.SidebarItem[];

export default defineConfig({
  title: 'test-inventory',
  description: 'Test metadata from source code, not from test results.',
  base: '/test-inventory/',
  cleanUrls: true,
  lastUpdated: true,
  srcExclude: ['**/README.md'],
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Reference', link: '/reference/output' },
      { text: 'API', link: '/api/' },
      { text: 'Changelog', link: '/changelog' },
      { text: 'About', link: '/about' },
    ],
    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Getting started', link: '/guide/getting-started' },
          { text: 'Examples', link: '/guide/examples' },
          { text: 'Command line', link: '/guide/cli' },
          { text: 'Library', link: '/guide/library' },
          { text: 'Query recipes', link: '/guide/recipes' },
          { text: 'CI recipes', link: '/guide/ci' },
          { text: 'Known limits', link: '/guide/limits' },
          { text: 'Compared with the runners', link: '/guide/runners' },
          { text: 'Real projects', link: '/guide/real-projects' },
        ],
      },
      {
        text: 'Reference',
        items: [
          { text: 'Output', link: '/reference/output' },
          { text: 'Supported syntax', link: '/reference/syntax' },
          { text: 'Diagnostics', link: '/reference/diagnostics' },
        ],
      },
      { text: 'API', items: apiSidebar },
    ],
    socialLinks: [
      { icon: 'github', link: 'https://github.com/Huldoser/test-inventory', ariaLabel: 'GitHub repository' },
      { icon: 'githubsponsors', link: 'https://github.com/sponsors/Huldoser', ariaLabel: 'Sponsor on GitHub' },
    ],
    editLink: {
      pattern: 'https://github.com/Huldoser/test-inventory/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },
    search: { provider: 'local' },
    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright © 2026 <a href="https://github.com/Huldoser">Andrey Rychkov</a>',
    },
  },
  // The JSON Schema is published next to the pages, at the URL in its $id.
  buildEnd(site) {
    const target = path.join(site.outDir, 'schema', 'v1.json');
    mkdirSync(path.dirname(target), { recursive: true });
    copyFileSync(path.resolve(site.root, '../schema/v1.json'), target);
  },
});
